set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm64)
set(triple arm64-linux-gnu)

set(CMAKE_C_COMPILER /home/mccakit/dev/llvm/bin/clang)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER /home/mccakit/dev/llvm/bin/clang++)
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_ASM_COMPILER /home/mccakit/dev/llvm/bin/clang)
set(CMAKE_ASM_COMPILER_TARGET ${triple})
set(CMAKE_RC_COMPILER /home/mccakit/dev/llvm/bin/llvm-rc)
set(CMAKE_LINKER_TYPE LLD)
set(CMAKE_AR /home/mccakit/dev/llvm/bin/llvm-ar)
set(CMAKE_RANLIB /home/mccakit/dev/llvm/bin/llvm-ranlib)
set(CMAKE_MT /home/mccakit/dev/llvm/bin/llvm-mt)

set(CMAKE_SYSROOT /home/mccakit/dev/sysroots/debian-arm64)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
add_compile_options(-cxx-isystem /home/mccakit/dev/libcxx/linux-arm64/include/c++/v1)
link_directories(/home/mccakit/dev/libcxx/linux-arm64/lib)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -L/home/mccakit/dev/libcxx/linux-arm64/lib -stdlib=libc++")
