set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR X86_64)
set(triple x86_64-apple-darwin)

set(CMAKE_C_COMPILER /home/mccakit/dev/llvm/bin/clang)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER /home/mccakit/dev/llvm/bin/clang++)
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_ASM_COMPILER /home/mccakit/dev/llvm/bin/clang)
set(CMAKE_ASM_COMPILER_TARGET ${triple})
set(CMAKE_RC_COMPILER /home/mccakit/dev/llvm/bin/llvm-rc)
set(CMAKE_RC_COMPILER_TARGET ${triple})
set(CMAKE_LINKER_TYPE LLD)
set(CMAKE_AR /home/mccakit/dev/llvm/bin/llvm-ar)
set(CMAKE_RANLIB /home/mccakit/dev/llvm/bin/llvm-ranlib)
set(CMAKE_MT /home/mccakit/dev/llvm/bin/llvm-mt)

set(CMAKE_INSTALL_NAME_TOOL /home/mccakit/dev/llvm/bin/llvm-install-name-tool)
set(CMAKE_OBJC_COMPILER /home/mccakit/dev/llvm/bin/clang)
set(CMAKE_OBJC_COMPILER_TARGET ${triple})
set(CMAKE_OBJCXX_COMPILER /home/mccakit/dev/llvm/bin/clang++)
set(CMAKE_OBJCXX_COMPILER_TARGET ${triple})

set(CMAKE_OSX_SYSROOT /home/mccakit/dev/sysroots/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk)
set(CMAKE_OSX_DEPLOYMENT_TARGET 14.0)
